name: CI – Dev & Release (WebGL)

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  dev-build:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calcular versão (dev)
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          IDS_FRJ=( $(git log $LAST_TAG..HEAD --grep 'FRJ-' --pretty=%s \
                    | grep -o 'FRJ-[0-9]\+' | sort -u) )
          IDS_SUS=( $(git log $LAST_TAG..HEAD --grep 'SUS-' --pretty=%s \
                    | grep -o 'SUS-[0-9]\+' | sort -u) )
          COUNT_FRJ=${#IDS_FRJ[@]}
          COUNT_SUS=${#IDS_SUS[@]}
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          SUMMARY="$LAST_TAG+f${COUNT_FRJ}s${COUNT_SUS}"
          KEY="${SUMMARY}-h${SHORT_COMMIT}"
          echo "FULL_VERSION_SUMMARY=$SUMMARY" >> $GITHUB_ENV
          echo "FULL_VERSION_KEY=$KEY"         >> $GITHUB_ENV

      - name: Setup Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2021.3.0f1
          activateLicense: true
          #modules: WebGL

      - name: Injetar BuildInfo
        run: |
          Unity -batchmode -projectPath . \
                -executeMethod BuildInfoGenerator.SetBuildInfo \
                -quit

      - name: Build WebGL (Dev)
        run: |
          Unity -batchmode -projectPath . \
                -buildTarget WebGL \
                -customBuildPath Builds/WebGL/dev \
                -quit

      - name: Upload Dev-WebGL artifact
        uses: actions/upload-artifact@v3
        with:
          name: Dev-WebGL
          path: Builds/WebGL/dev

  release-build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calcular versão (release)
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          IDS_FRJ=( $(git log $LAST_TAG..HEAD --grep 'FRJ-' --pretty=%s \
                    | grep -o 'FRJ-[0-9]\+' | sort -u) )
          IDS_SUS=( $(git log $LAST_TAG..HEAD --grep 'SUS-' --pretty=%s \
                    | grep -o 'SUS-[0-9]\+' | sort -u) )
          COUNT_FRJ=${#IDS_FRJ[@]}
          COUNT_SUS=${#IDS_SUS[@]}
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          SUMMARY="$LAST_TAG+f${COUNT_FRJ}s${COUNT_SUS}"
          KEY="${SUMMARY}-h${SHORT_COMMIT}"
          echo "FULL_VERSION_SUMMARY=$SUMMARY" >> $GITHUB_ENV
          echo "FULL_VERSION_KEY=$KEY"         >> $GITHUB_ENV

      - name: Setup Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2021.3.0f1
          activateLicense: true

      - name: Injetar BuildInfo
        run: |
          Unity -batchmode -projectPath . \
                -executeMethod BuildInfoGenerator.SetBuildInfo \
                -quit

      - name: Build WebGL (Release)
        run: |
          Unity -batchmode -projectPath . \
                -buildTarget WebGL \
                -customBuildPath Builds/WebGL/release \
                -quit

      - name: Upload Release-WebGL artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release-WebGL
          path: Builds/WebGL/release
