name: CI – Build WebGL

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    #runs-on: ubuntu-latest

    if: >
      (github.event_name == 'push' &&
       (startsWith(github.ref, 'refs/heads/main') ||
        startsWith(github.ref, 'refs/heads/dev')) &&
       contains(github.event.head_commit.message, 'BUILD'))
      ||
      (github.event_name == 'pull_request' &&
       contains(github.event.pull_request.title, 'BUILD'))

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setting Version in Scriptable
        shell: bash
        run: |
          git fetch --prune --tags

          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          if [ "$LAST_TAG" = "v0.0.0" ]; then
            RANGE="HEAD"
          else
            RANGE="$LAST_TAG..HEAD"
          fi

          # Esses || true garantem que o pipeline não quebre se não houver matches
          IDS_FRJ=( $(
            git log "$RANGE" --grep 'FRJ-' --pretty=%s \
              | grep -o 'FRJ-[0-9]\+' || true \
              | sort -u
          ) )
          IDS_SUS=( $(
            git log "$RANGE" --grep 'SUS-' --pretty=%s \
              | grep -o 'SUS-[0-9]\+' || true \
              | sort -u
          ) )

          COUNT_FRJ=${#IDS_FRJ[@]}
          COUNT_SUS=${#IDS_SUS[@]}
          SHORT_COMMIT=$(git rev-parse --short HEAD)

          SUMMARY="$LAST_TAG+f${COUNT_FRJ}s${COUNT_SUS}"
          KEY="${SUMMARY}-h${SHORT_COMMIT}"

          echo "FULL_VERSION_SUMMARY=$SUMMARY" >> $GITHUB_ENV
          echo "FULL_VERSION_KEY=$KEY"         >> $GITHUB_ENV

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL:   ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion:   2022.3.61f1
          targetPlatform: WebGL
          projectPath:    .
          buildName:      WebGL

      - name: Upload WebGL artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-WebGL-${{ github.ref_name }}
          path: build/WebGL
