name: CI – Build WebGL

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      (startsWith(github.ref, 'refs/heads/main') ||
       startsWith(github.ref, 'refs/heads/dev') ||
       github.event_name == 'pull_request') &&
      (contains(github.event.head_commit.message, 'BUILD') ||
       contains(github.event.pull_request.title, 'BUILD'))

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calcular versão
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          IDS_FRJ=( $(git log $LAST_TAG..HEAD --grep 'FRJ-' --pretty=%s \
                    | grep -o 'FRJ-[0-9]\+' | sort -u) )
          IDS_SUS=( $(git log $LAST_TAG..HEAD --grep 'SUS-' --pretty=%s \
                    | grep -o 'SUS-[0-9]\+' | sort -u) )
          COUNT_FRJ=${#IDS_FRJ[@]}
          COUNT_SUS=${#IDS_SUS[@]}
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          SUMMARY="$LAST_TAG+f${COUNT_FRJ}s${COUNT_SUS}"
          KEY="${SUMMARY}-h${SHORT_COMMIT}"
          echo "FULL_VERSION_SUMMARY=$SUMMARY" >> $GITHUB_ENV
          echo "FULL_VERSION_KEY=$KEY"         >> $GITHUB_ENV

      - name: Build WebGL with Unity Builder
        uses: game-ci/unity-builder@v2
        env:
          # para Personal License
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # ou Professional License
          UNITY_EMAIL:   ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD:${{ secrets.UNITY_PASSWORD }}
        with:
          # plataforma alvo
          targetPlatform: WebGL
          # pasta base do projeto (onde está Assets/)
          projectPath:    .
          # optional: nome da pasta de saída (default é WebGL)
          buildName:      WebGL

      - name: Upload WebGL artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-WebGL-${{ github.ref_name }}
          path: build/WebGL
